### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wjquigs11** [nauti-control/STWirelessRemote#2]
I get several errors compiling in VS Code. Most of the errors are for missing include files because they're referenced with "\" instead of "/" which is easy to fix, but I also got a link error:
Linking .pio/build/nodemcu-32s/firmware.elf
.pio/build/nodemcu-32s/lib1e2/libEspSoftwareSerial.a(SoftwareSerial.cpp.o): in function `std::function<void ()>::operator()() const':
/Users/user/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:686:(.iram1.66[delegate::detail::DelegateImpl<void*, void>::operator()() const]+0x24): dangerous relocation: l32r: literal placed after use: .literal._ZNK8delegate6detail12DelegateImplIPvvEclEv
collect2: error: ld returned 1 exit status
*** [.pio/build/nodemcu-32s/firmware.elf] Error 1
======================================================= [FAILED] Took 13.16 seconds =======================================================

I don't really understand why, but google turned up [this](https://stackoverflow.com/questions/19532826/what-does-a-dangerous-relocation-error-mean), so I modified platformio.ini and added:

build_flags =
	-mtext-section-literals

Let me know if you want a pull request.

**Comment by nauti-control** [comment]
I'm fairly new to PlatformIO so may well be down to me! I'm not having issues and switching over to check that branch now just to make sure . Would there be some other settings in our visual code/platformio that could affect this?

First thing is that the software serial library looks to be at fault in your message, you'd expect that should just work without issue. 

It's a strange one! I'd like to understand why the difference in behaviour though.

**Comment by nauti-control** [comment]
*  Executing task in folder STWirelessRemote: C:\Users\user\.platformio\penv\Scripts\platformio.exe run --environment nodemcu-32s 

Processing nodemcu-32s (platform: espressif32; board: nodemcu-32s; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 (5.3.0) > NodeMCU-32S
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20006.221224 (2.0.6)
 - tool-esptoolpy @ 1.40400.0 (4.4.0)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 39 compatible libraries
Scanning dependencies...
Dependency Graph
|-- rc-switch @ 2.6.4
|-- ESP Async WebServer @ 1.2.3+sha.f71e3d4
|-- EspSoftwareSerial @ 7.0.0
|-- I2Cdevlib-HMC5883L @ 1.0.0
|-- SPIFFS @ 2.0.0
|-- AsyncTCP @ 1.1.1
|-- WiFi @ 2.0.0
|-- Preferences @ 2.0.0
Building in release mode
Compiling .pio\build\nodemcu-32s\src\Lib\BoxWebServer.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\BoxWifi.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\CommandStack.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\Nmea.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\NmeaServer.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\Options.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\RemoteControl.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\SeaTalk.cpp.o
Compiling .pio\build\nodemcu-32s\src\Lib\SignalManager.cpp.o
Compiling .pio\build\nodemcu-32s\src\main.cpp.o
Building .pio\build\nodemcu-32s\bootloader.bin
Generating partitions .pio\build\nodemcu-32s\partitions.bin
esptool.py v4.4
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Compiling .pio\build\nodemcu-32s\libe60\rc-switch\RCSwitch.cpp.o
Compiling .pio\build\nodemcu-32s\libd4f\AsyncTCP\AsyncTCP.cpp.o
Compiling .pio\build\nodemcu-32s\lib5e1\FS\FS.cpp.o
Compiling .pio\build\nodemcu-32s\lib5e1\FS\vfs_api.cpp.o
Archiving .pio\build\nodemcu-32s\libe60\librc-switch.a
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFi.cpp.o
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiAP.cpp.o
Archiving .pio\build\nodemcu-32s\libd4f\libAsyncTCP.a
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiClient.cpp.o
Archiving .pio\build\nodemcu-32s\lib5e1\libFS.a
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiSTA.cpp.o
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiScan.cpp.o
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiServer.cpp.o
Compiling .pio\build\nodemcu-32s\lib152\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\AsyncEventSource.cpp.o
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\AsyncWebSocket.cpp.o
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\SPIFFSEditor.cpp.o
Archiving .pio\build\nodemcu-32s\lib152\libWiFi.a
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\WebAuthentication.cpp.o
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\WebHandlers.cpp.o
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\WebRequest.cpp.o
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\WebResponses.cpp.o
Compiling .pio\build\nodemcu-32s\lib953\ESP Async WebServer\WebServer.cpp.o
Compiling .pio\build\nodemcu-32s\libe20\EspSoftwareSerial\SoftwareSerial.cpp.o
Compiling .pio\build\nodemcu-32s\lib8eb\Wire\Wire.cpp.o
Compiling .pio\build\nodemcu-32s\lib48a\I2Cdevlib-Core\I2Cdev.cpp.o
Archiving .pio\build\nodemcu-32s\lib953\libESP Async WebServer.a
Compiling .pio\build\nodemcu-32s\libf8d\I2Cdevlib-HMC5883L\HMC5883L.cpp.o
Archiving .pio\build\nodemcu-32s\libe20\libEspSoftwareSerial.a
Compiling .pio\build\nodemcu-32s\lib6d2\SPIFFS\SPIFFS.cpp.o
Archiving .pio\build\nodemcu-32s\lib8eb\libWire.a
Compiling .pio\build\nodemcu-32s\lib41d\Preferences\Preferences.cpp.o
Archiving .pio\build\nodemcu-32s\lib48a\libI2Cdevlib-Core.a
Compiling .pio\build\nodemcu-32s\FrameworkArduino\Esp.cpp.o
Archiving .pio\build\nodemcu-32s\libf8d\libI2Cdevlib-HMC5883L.a
Compiling .pio\build\nodemcu-32s\FrameworkArduino\FirmwareMSC.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\FunctionalInterrupt.cpp.o
Archiving .pio\build\nodemcu-32s\lib6d2\libSPIFFS.a
Compiling .pio\build\nodemcu-32s\FrameworkArduino\HWCDC.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\HardwareSerial.cpp.o
Archiving .pio\build\nodemcu-32s\lib41d\libPreferences.a
Compiling .pio\build\nodemcu-32s\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\IPv6Address.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\Print.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\StreamString.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\USB.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\USBCDC.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\USBMSC.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\WString.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\base64.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-adc.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-bt.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-cpu.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-dac.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-gpio.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-i2c-slave.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-i2c.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-ledc.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-matrix.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-misc.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-psram.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-rgb-led.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-rmt.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-sigmadelta.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-spi.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-time.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-timer.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-tinyusb.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-touch.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\esp32-hal-uart.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\firmware_msc_fat.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\libb64\cdecode.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\libb64\cencode.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\main.cpp.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\stdlib_noniso.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\wiring_pulse.c.o
Compiling .pio\build\nodemcu-32s\FrameworkArduino\wiring_shift.c.o
Archiving .pio\build\nodemcu-32s\libFrameworkArduino.a
Linking .pio\build\nodemcu-32s\firmware.elf
Retrieving maximum program size .pio\build\nodemcu-32s\firmware.elf
Checking size .pio\build\nodemcu-32s\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  13.6% (used 44616 bytes from 327680 bytes)
Flash: [======    ]  63.9% (used 837349 bytes from 1310720 bytes)
Building .pio\build\nodemcu-32s\firmware.bin
esptool.py v4.4
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.
========================================================================== [SUCCESS] Took 79.63 seconds ==========================================================================
 *  Terminal will be reused by tasks, press any key to close it.
