### ISSUE TITLE
Port to SignalK SensESP

### ISSUE THREAD

**Issue by UnderSampled** [nauti-control/STWirelessRemote#3]
For more complicated boat networks, where existing NMEA0183, NMEA2000, Seatalk, wifi, USB, and bluetooth devices all live together, SignalK is meant to help bridge the interfaces with a common server.

Info about the SignalK project: http://signalk.org/

In addition to the server, the SignalK project also maintains a framework for ESP-based sensors to communicate with it. It is well thought out, with a dashboard in the default access-point mode for configuring wifi and (optional) connection to the server, and an asynchronous event-based architecture from ReactESP.

GitHub for the SensESP firmware framework: https://github.com/SignalK/SensESP

ReactESP: https://github.com/mairas/ReactESP

Because the rest of SenseESP is quite similar to this project (PlatformIO, Arduino/C++, an ESP32, and ESP Async Webserver), I believe that porting to their codebase will not be difficult, and is the easiest way to gain some important functionality.

---

For my own part, I need SignalK for my connection to SeaTalk to be useful, as my ultimate goal is to provide the GPS, and course for "track" mode through SignalK. As well, I look forward to finally getting wind and autopilot data into SignalK, so it can be shown in Freeboard (a locally hosted web-based chartplotter) and OpenCPN combined with the AIS data.

I have been trying to do this for several years, and already had a non-functional prototype. I was able to get your firmware on it, but I still have some hardware issues to work out that prevent me from contributing already.

**Comment by nauti-control** [comment]
Hi there, yes i have worked with signal K before . One thing you'll notice when working with ESP32 a bit if you have a bluetooth and web (async libraries) you soon run out of heap space and things start turning a bit quirky so i'm trying to avoid adding more bloat.

In version 2 that i'm currently working on and will be available to supporters first will have wireless connection abilities with TCPIP so will connect to open marine and interface through signal K using NMEA 0183 async TCPIP . There are however other things such as connecting directly to OPEN CPN that this would support from a laptop/tablet etc and other apps such as navionics. I'd rather not focus on one particular use case , though I do feel  what you are looking will be covered by what i'm doing.

I'll hopefully get some demos up on the socials and website on version two working with Signal K for the data points such as wind speed etc.

**Comment by UnderSampled** [comment]
Will this be bi-directional? Providing the GPS and track data to my autopilot would be a huge improvement!

On February 26, 2024 5:28:16 AM EST, Nauti-Control ***@***.***> wrote:
>Hi there, yes i have worked with signal K before . One thing you'll notice when working with ESP32 a bit if you have a bluetooth and web (async libraries) you soon run out of heap space and things start turning a bit quirky so i'm trying to avoid adding more bloat.
>
>In version 2 that i'm currently working on and will be available to supporters first will have wireless connection abilities with TCPIP so will connect to open marine and interface through signal K using NMEA 0183 async TCPIP . There are however other things such as connecting directly to OPEN CPN that this would support from a laptop/tablet etc and other apps such as navionics. I'd rather not focus on one particular use case , though I do feel  what you are looking will be covered by what i'm doing.
>
>I'll hopefully get some demos up on the socials and website on version two working with Signal K for the data points such as wind speed etc.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nauti-control/STWirelessRemote/issues/3#issuecomment-1963787631
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Sincerely,
UnderSampled
